name: DirectorySync

on:
    schedule:
        -   cron: "0 18 * * *"
    workflow_dispatch:

jobs:

    Logger:
        uses: EncoreDigitalGroup/.github/.github/workflows/directorySync.yml@v1
        with:
            source: 'src/Logger/docs/'
            targetRepo: 'encoredigitalgroup/docs.encoredigitalgroup.com'
            targetDirectory: 'docs/Code/PHP/Packages/PHPGenesis/Logger'
        secrets:
            token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}

    Services_AmazonWebServices:
        uses: EncoreDigitalGroup/.github/.github/workflows/directorySync.yml@v1
        with:
            source: 'src/Services/AmazonWebServices/docs/'
            targetRepo: 'encoredigitalgroup/docs.encoredigitalgroup.com'
            targetDirectory: 'docs/Code/PHP/Packages/PHPGenesis/Services/AmazonWebServices'
        secrets:
            token: ${{ secrets.GH_GENERAL_ACCESS_TOKEN }}