name: SplitMonorepo

on:
    workflow_call:
        secrets:
            GH_MONOREPO_SPLIT_TOKEN:
                description: "GitHub Access Token"
                required: true

permissions: write-all

jobs:
    SplitMonorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    -   localPath: Common
                        splitRepoName: Common

                    -   localPath: Laravel
                        splitRepoName: Laravel

                    -   localPath: Logger
                        splitRepoName: Logger

                    -   localPath: Http
                        splitRepoName: Http

                    -   localPath: DevUtilities
                        splitRepoName: DevUtilities

                    -   localPath: Services/AmazonWebServices
                        splitRepoName: AmazonWebServices
        steps:
            -   uses: actions/checkout@v3
            -   id: previousTag
                uses: 'WyriHaximus/github-action-get-previous-tag@master'

            -   name: Monorepo Split of ${{ matrix.package }}
                uses: danharrin/monorepo-split-github-action@v2.3.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_MONOREPO_SPLIT_TOKEN }}
                with:
                    package_directory: 'src/${{ matrix.package.localPath }}'
                    repository_organization: 'EncoreDigitalGroup'
                    repository_name: '${{ matrix.package.splitRepoName }}'
                    branch: main
                    tag: ${{ steps.previousTag.outputs.tag }}
                    user_name: 'GenesisBot'
                    user_email: 'ghbot@phpgenesis.com'