name: SplitMonorepo

on:
    workflow_call:
        secrets:
            GH_MONOREPO_SPLIT_TOKEN:
                description: "GitHub Access Token"
                required: true
    workflow_dispatch:
        inputs:
            version:
                description: "Version tag to use for the split"
                required: true
                type: string

permissions: write-all

jobs:
    SplitMonorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package:
                    -   localPath: Common
                        splitRepoName: Common

                    -   localPath: DateTime
                        splitRepoName: DateTime

                    -   localPath: Laravel
                        splitRepoName: Laravel

                    -   localPath: Logger
                        splitRepoName: Logger

                    -   localPath: Http
                        splitRepoName: Http

                    -   localPath: DevUtilities
                        splitRepoName: DevUtilities

                    -   localPath: CloudProviders/AmazonWebServices
                        splitRepoName: AmazonWebServices
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.event_name == 'workflow_dispatch' && inputs.version || '' }}
                    fetch-depth: 0
            -   id: previousTag
                if: github.event_name != 'workflow_dispatch'
                uses: 'WyriHaximus/github-action-get-previous-tag@master'

            -   name: Monorepo Split of ${{ matrix.package }}
                uses: danharrin/monorepo-split-github-action@v2.4.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_MONOREPO_SPLIT_TOKEN }}
                with:
                    package_directory: 'src/${{ matrix.package.localPath }}'
                    repository_organization: 'PHPGenesis'
                    repository_name: '${{ matrix.package.splitRepoName }}'
                    branch: main
                    tag: ${{ inputs.version || steps.previousTag.outputs.tag }}
                    user_name: 'GenesisBot'
                    user_email: 'ghbot@phpgenesis.com'